export const BLOG_DIRECTORY_EPIC = 'BLOG_DIRECTORY_EPIC';
export const BLOG_DIRECTORY_REDUCER = 'BLOG_DIRECTORY_EPIC';
export const BLOG_INFO_EPIC = 'BLOG_INFO_EPIC';
export const BLOG_INFO_REDUCER = 'BLOG_INFO_EPIC';
